<?php
session_start();
header('Content-type:text/html;charset=gb2312');
define('DB_HOST','localhost');
define('DB_USER','root');
define('DB_PASSWORD','');
define('DB_DATABASE','bbs');
define('DB_PORT',3306);
?>