/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class judgeString */

#ifndef _Included_judgeString
#define _Included_judgeString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     judgeString
 * Method:    getSolution
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_judgeString_getSolution
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
